### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by danielf** [ef363/FFT#3]
Make sure you test not only accuracy but also speed. For instance, you don't need to recompute the twiddle in every iteration of FFT (which uses the math.exp function, that while it is O(1), it is pretty slow). You can compute the new value using the previous one by a simple multiplication.

It would be good to have a framework that times different parts of the software and outputs a report, so that you know where to spend time tuning for speed.

**Comment by OnionBubs** [comment]
We've updated the FFT to compute the twiddle more effectively as was taught in class.  We still need to output a profile.

**Comment by danielf** [comment]
You need a systematic way to profile your code. Create code to do the profiling!

Also, always think about what you are doing. In particular: Y += [Ynew] is more expensive than Y.append(Ynew), but both are unnecessarily expensive given that you know the final length of Y at the beginning of the DFT call.

**Comment by daveckman** [comment]
We made Y a fixed length numpy array (uninitialized). Still need to do more profiling.

**Comment by danielf** [comment]
That's awesome, I will close this issue for now.
