### ISSUE TITLE
Convert to numpy

### ISSUE THREAD

**Issue by danielf** [ef363/FFT#6]
Convert to numpy arrays for extra performance. Lists can hold any kind of object (for instance: l = [2, "FFT"] is perfectly valid in Python). Because of that they have to be implemented using pointers which takes out a lot of your performance.

Numpy arrays are homogeneous (every entry is a double, or an integer, etc...) so it can maintain the array in a contiguous part of memory! Also, you can allocate non initialized data with numpy.

**Comment by daveckman** [comment]
We converted the output (Y) to a numpy array. We'll explore changing the input (X) to numpy array for further speed-ups.
