### ISSUE TITLE
Take care of the files you add

### ISSUE THREAD

**Issue by danielf** [ef363/FFT#7]
There is a new file in the git repository called ".fft.py.swp". This is a vim temporary file that is created while fft.py is opened.

Do not add files using "git add ." if you don't know what will happen. This file should have never been included in the repo.

Remember to use the .gitignore file to exclude, for instance, all the ".swp" files. (http://git-scm.com/docs/gitignore)

**Comment by daveckman** [comment]
".swp" files are now listed in the .gitignore file. The "fft.py.swp" file has been removed from the git repository.
