### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by danielf** [ef363/FFT#8]
The code is amazing, good job!

The only three comments I would make are:

1) Put a reference to "the paper" at ilt.py. I know it is in README as well, but it would make it easier for other people to read your code.
2) "We're not sure why we are off by a factor of 2". Try to figure out :)
3) Now that you have a working copy, do some performance analysis to make sure that the runtime complexity is indeed O(n log n). The plot of the graph should look like c*n log n + o(n log n) for some constant c.
4) Python is notoriously slow when doing loops. Try your best to avoid them, using list comprehensions instead. You are already doing a good job at this, I'm making this point on the sense that "there is always something to improve".

Once again, good job!

**Comment by venuslo** [comment]
1.  Done
2.  We looked over the paper and it seems there's a mistake.
3.  Done, we did plots for ILT and FFT (actual time and log plots).  They look nice :)
4.  Done

Others comments- test_fft.py file:  We added one more test to FFT for a longer vector (testCatastrophicLarge).  Using Python's numpy.fft.fft function actually results in catastrophic annihilation on the first term (evaluates to 0) whereas our fft.FFT function correctly computes it as 1.  Hence we used a high error tolerance in this unittest.
